import { Prisma } from '@prisma/client';

export const SelectGeneralCustomerOrder: Prisma.OrderSelect = {
  id: true,
  voucherId: true,
  exchangePoint: true,
  customerId: true,
  paymentMethod: true,
  uuid: true,
  trackId: true,
  createdAt: true,
  status: true,
  orderAddress: {
    select: {
      address: true,
      city: true,
    },
  },
  orderProduct: {
    select: {
      id: true,
      uuid: true,
      serviceType: true,
      packageType: true,
      deviceId: true,
      name: true,
      category: true,
      description: true,
      price: true,
      quantity: true,
      discount: true,
      createdAt: true,
      updatedAt: true,
      deletedAt: true,
      orderProductId: true,
      orderProductUuid: true,
      orderProductVariantId: true,
      orderProductVariantUuid: true,
      orderId: true,
      bundleGroupId: true,
      sourcePackageType: true,
      bundleName: true,
      minusPrice: true,
      bundleImage: true,
      variantId: true,
      variantUuid: true,
      variantName: true,
      variantCode: true,
      variantImage: true,
      orderProductImage: {
        select: {
          uuid: true,
          url: true,
        },
      },
    },
  },
  subTotalPay: true,
  voucherDiscount: true,
  deliveryFee: true,
  totalPayment: true,
  expiredAt: true,
};
